#!/usr/bin/env php
<?php

namespace crudgen;

//! crudgen version
define('CRUDGEN_VERSION', '2.0.0');
define('TIME_BEGIN', microtime(true));

//! current dir
$dir = strtr(__DIR__, '\\', '/').'/';

//! config
$cfg     = isset($_SERVER['argv'][2])?$_SERVER['argv'][2]:
    $dir . '/moegen/config.ini';

(is_file($cfg) && $CONFIG = parse_ini_file($cfg, true)) ||
    exit('Invalid configuration file!');

$alt = array(
    'crudgen'=>$dir.'src/',
    'moegen'=>$dir.'moegen/'
    );
!isset($CONFIG['namespaces_lookup']) || $alt += $CONFIG['namespaces_lookup'];

spl_autoload_register(function($c) use ($alt) {
    $ns = $fp = '';
    foreach (explode('\\', ltrim(substr($c, 0, strrpos($c, '\\')), '\\'))
        as $key => $value)
    {
        $ns .= $value;
        if (isset($alt[$ns])) {
            $fp = strtr($alt[$ns].str_replace($ns, '', $c), '\\', '/').'.php';
            break;
        }
        $ns .= '\\';
    }
    if (file_exists($fp))
        require $fp;
});

C::config(array('generator'=>array('template'=>$dir.'moegen/')));
C::config($CONFIG);

C::header('Script Generator tools'.C::eol().
    'Version '.CRUDGEN_VERSION.C::eol().
    'By eghojansu'.C::eol(2).
    'enjoy it...!');

C::start('Performing action...', 0, 1);
    ob_start();
    (new Crudgen(isset($_SERVER['argv'][1])?$_SERVER['argv'][1]:null))->run();
    C::shiftAll(ob_get_clean(), 1);
C::finish();

C::footprint();
exit(0);
